
name: Deploy Resume

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1  # Use your preferred region here
      
      - name: Copy files to S3 bucket
        run: |
          aws s3 sync . s3://your-resume-bucket --exclude ".git/*" --exclude ".github/*"
      
      - name: Create deployment info file
        run: |
          echo "{\"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"commit\": \"${{ github.sha }}\"}" > deployment-info.json
          aws s3 cp deployment-info.json s3://resume-frontend-dev-lucas/
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1PRUZMQ6349DR --paths "/*"
