name: Deploy Resume

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
          
      - name: Deploy website to S3
        run: |
          aws s3 cp index.html s3://resume-frontend-dev-lucas/ --cache-control "max-age=3600"
          
      - name: Update deployment timestamp
        run: |
          echo "DEPLOY_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          
      - name: Create deployment record
        run: |
          echo "{\"lastDeploy\":\"${{ env.DEPLOY_TIMESTAMP }}\"}" > deployment-info.json
          aws s3 cp deployment-info.json s3://resume-frontend-dev-lucas/
